# .github/workflows/regen_embeddings.yml
name: Regenerar Embeddings

# Ejecuta cada día a las 02:00 AM Bogotá (07:00 UTC) y también permite disparo manual
on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  regen:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION:            ${{ secrets.AWS_REGION }}
      S3_BUCKET:             ${{ secrets.S3_BUCKET }}
      S3_KEY:                ${{ secrets.S3_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies for dlib
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libboost-python-dev libboost-thread-dev

      - name: Set up Python 3.8.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dlib
          pip install boto3 insightface scikit-learn opencv-python tqdm jupyter nbconvert

      - name: Convert notebook to script
        run: |
          jupyter nbconvert --to script facialRecognition/entrenamiento_guardado.ipynb --output entrenamiento_guardado

      - name: Run embeddings regeneration
        run: |
          python entrenamiento_guardado.py

      - name: Verify upload
        run: |
          aws s3 ls s3://$S3_BUCKET/$S3_KEY
