```yaml
# .github/workflows/regen_embeddings.yml
name: Regenerar Embeddings

# Ejecuta cada día a las 02:00 AM Bogotá (07:00 UTC) y permite disparo manual
on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  regen:
    # Usamos ubuntu-latest y conda para Python 3.8.10
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION:            ${{ secrets.AWS_REGION }}
      S3_BUCKET:             ${{ secrets.S3_BUCKET }}
      S3_KEY:                ${{ secrets.S3_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniconda and Python 3.8.10
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.8.10'
          activate-environment: regen-env
          auto-activate-base: false

      - name: Install dependencies via conda
        run: |
          conda install -n regen-env -y -c conda-forge \
            dlib boto3 insightface scikit-learn opencv tqdm jupyter nbconvert

      - name: Convert notebook to script
        run: |
          conda run -n regen-env jupyter nbconvert --to script \
            facialRecognition/entrenamiento_guardado.ipynb --output entrenamiento_guardado

      - name: Run entrenamiento_guardado
        run: |
          conda run -n regen-env python entrenamiento_guardado.py

      - name: Verify upload to S3
        run: |
          aws s3 ls s3://$S3_BUCKET/$S3_KEY
```
